#!/usr/bin/env python

"""
    Setup script for OpenRadiac calculations.
  
   
    Written by Carlos A. Gimenez, Natural and Exact Science Faculty
                                  Northeastern University of Argentina,
        			              Corrientes, Argentina
   
    Contributors: --
   
    Environment variables used by pam:
             DIRTIMEOUT        - time out limit for OpenMind run
          
"""
 
import os
import sys
import subprocess

if sys.version < '2.4':
    print('pam requires python version >= 2.4')
    sys.exit(1)

class set_enviroment:
  """
  class for handling the  OpenRadiac setup
  """
  def __init__(self):
    """
    Initialize the global set of variables
    """
  def main_run(self):
    src = os.getcwd() 
    os.system("cmake -DCMAKE_BUILD_TYPE=RELEASE")
    print "runing cmake"
    os.system("make")
    print "done"
set_enviroment().main_run()
print "The AMCalc code is ready, enjoy your meal"
