#!/usr/bin/env python

import os
import sys
import os.path as path
import shutil
import pathlib

if sys.version < '3.5':

    print('run_kernel requires python version >= 3.5')

    sys.exit(1)

class kind_run(object):

    def __init__(self):

        """
        Main driver for run the code
        """

    def __input__run__(self):

        print("Choose what kind of run you want...")

        print("0 - Install")

        print("1 - Run Test")

        print("2 - Score data basis")

        print("3 - Clean test folder")

        print("4 - Debug")

        gkind = input("What is your election?")

        print("Your election was: "+ gkind)

        return gkind

    def __choose_run__(self):

        self.gkind = kind_run().__input__run__()

        if (self.gkind == "0"):

            print(" Installing... ")

            compile_code()

            print("Correctly instaled...")

        elif (self.gkind == "1"):

            print(" Running Test... ")

            set_enviroment().__clean_out__()

            self.test_path = os.getcwd() + "/test/run_test"

            os.mkdir(self.test_path)

            run_test().__test_kind__(self.gkind)

        elif (self.gkind == "2"):

            print(" Scoring data basis...")

            run_test().__test_kind__(self.gkind)

        #elif (self.gkind == "3"):

        #   print(" Scoring as BOT...")

        #    run_test().__test_kind__(self.gkind)

        elif (self.gkind == "3"):

            set_enviroment().__clean_out__()

        elif (self.gkind == "4"):

            print(" Debugging: Training Neural Network...")

            set_enviroment().__clean_out__()

            compile_code()

            print("Correctly instaled...")

            self.test_path = os.getcwd() + "/test/run_test"

            os.mkdir(self.test_path)

            run_test().__test_kind__(self.gkind)

class compile_code(object):

    """
    Compile code with make
    """

    def __init__(self):

        self.src = os.getcwd() 

        self.build = self.src+"/build"

        print("Build in:")

        print(self.build)

        if os.path.exists(self.build):

            print("Cleaning Folder /build ")

            shutil.rmtree(self.build)

        os.mkdir(self.build)

        os.chdir(self.build)

        print("Running cmake configurations...")

        os.system("cmake ..")

        print("Running make installation...")

        os.system("make")
        

class run_test(object):

    def __init__(self):

        """
        Set the kernel code
        """

    def __test_kind__(self,kind):

        self.kind = kind
   
        self.build_path = os.getcwd()+ "/test/run_test"

        print("Run Forest...")

        set_enviroment().__get_exe__()

        set_enviroment().__get_example__(self.kind)

        os.chdir(self.build_path)

        print("wut?")

        print(self.build_path)

        os.system("./OpenMind.exe")

class set_enviroment(object):
    """
    class for handling the NN_Kernel
    """
    def __init__(self):
        """
        Initialize the global set of variables
        """

    def __get_exe__(self):

        test_path = os.getcwd() + "/test/run_test"

        shutil.copy(os.getcwd()+"/build/src/OpenMind.exe", test_path) 
  
    def __get_example__(self, kind):

        self.kind = kind

        test_path = os.getcwd() + "/test/run_test"

        example_path = os.getcwd() + "/test/example/"

        if (self.kind == "1"):

            shutil.copy(example_path + "Kernel_Train.inp", test_path+"/Kernel.inp") 

            shutil.copy(example_path + "iris.csv", test_path)

        elif (self.kind == "2"):

            if os.path.exists(test_path+"\iris_scored.csv"):

                os.remove(test_path+"\iris_scored.csv")

            shutil.copy(example_path + "Kernel_Basis.inp", test_path+"/Kernel.inp") 

            shutil.copy(example_path + "iris.csv", test_path)

        elif (self.kind == "4"):

            if os.path.exists(test_path+"\iris_scored.csv"):

                os.remove(test_path+"\iris_scored.csv")

            shutil.copy(example_path + "Kernel_Train_debug.inp", test_path+"/Kernel.inp") 

            shutil.copy(example_path + "iris.csv", test_path)

    def __clean_out__(self):

        print("Cleaning test...")

        self.test_path = os.getcwd() + "/test/run_test"

        print(self.test_path)

        if os.path.exists(self.test_path):

            print("Cleaning Folder /test/run_test ")

            shutil.rmtree(self.test_path)

        print("done!")

kind_run().__choose_run__()